site_name: Learning MQTT
site_url: https://github.com/acme-iot/learning-mqtt
site_description: List of MQTT learning resources
site_author: tmillar
repo_name: acme-iot/learning-mqtt
repo_url: https://github.com/acme-iot/learning-mqtt
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/acme-iot
extra_css:
    - css/extra.css
nav:
  - "Learning MQTT": "index.md"
